name: E2E Scenario

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  LName: "Skirt & Top"
  LExpectedName: "Skirt & Top"
  LExpectedPrice: "$500"
  LExpectedQty: "1"
  LExpectedTotalPrice: "$500"

  Name: "Long Frock"
  ExpectedName: "Long Frock"
  ExpectedPrice: "$100"
  ExpectedQty: "1"
  ExpectedTotalPrice: "$100"

jobs:
  Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn clean test -Dtest=TC16_OrderConfirmationTest "-DexecutionType=LocalHeadless" "-DConfirmationProduct.Name=${{ env.LName }}" "-DConfirmationProduct.ExpectedName=${{ env.LExpectedName }}" "-DConfirmationProduct.ExpectedPrice=${{ env.LExpectedPrice }}" "-DConfirmationProduct.ExpectedQty=${{ env.LExpectedQty }}" "-DConfirmationProduct.ExpectedTotalPrice=${{ env.LExpectedTotalPrice }}"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Linux_Chrome_Report
          path: "test-output/reports/*.html"

  Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Running Tests
        continue-on-error: true
        run: mvn clean test -Dtest=TC16_OrderConfirmationTest "-DexecutionType=LocalHeadless" "-DConfirmationProduct.Name=${{ env.Name }}" "-DConfirmationProduct.ExpectedName=${{ env.ExpectedName }}" "-DConfirmationProduct.ExpectedPrice=${{ env.ExpectedPrice }}" "-DConfirmationProduct.ExpectedQty=${{ env.ExpectedQty }}" "-DConfirmationProduct.ExpectedTotalPrice=${{ env.ExpectedTotalPrice }}"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Windows_Edge_Report
          path: "test-output/reports/*.html"
